### ISSUE TITLE
Aimbot!

### ISSUE THREAD

**Issue by DeadLuck1** [degeneratehyperbola/NEPS#1] opened 2021-03-24 22:23 UTC
the aimbot is basically fucked it will lock sometimes idk why I've looked through the code and could not find why. the aimbot will lock sometimes even if the bot/player is in front of u

**Comment by DeadLuck1** [comment] 2021-03-24 22:24
other then this issue the cheat works fine

**Comment by degeneratehyperbola** [comment] 2021-03-26 15:47
Thanks for pointing it out, it wasn't causing any problems on debug builds so I did not notice.
Fixed in 341db97ea63bccbc5f9fa5916847bd37093c6b2e

**Closed by degeneratehyperbola** 2021-03-26 15:47 UTC

**Comment by degeneratehyperbola** [comment] 2021-03-26 15:49
If you are curious, this problem was caused by the ray struct not being fully initialized. In best case scenario it won't do anything as in debug builds, in worst it would crash.
